sudo: requiresd
services:
  - docker

before_install:
  - docker build -t mlgthe1/deploy-cloud -f Dockerfile.dev .

script:
  - docker run mlgthe1/deploy-cloud yarn test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "deploy-cloud"
  env: "DeployCloud-env"
  bucket_name: "elasticbeanstalk-us-east-2-341448331141"
  bucket_path: "deploy-cloud"
  # deploy only when the master branch has a new commit
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"