version: '3'
services:
  react-app:
    build:
    #context is the to look in the current directory
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4002:3000"
    volumes:
    #/app/node_modules means that it must not
    # inludes this node_modules already existant in
    #the container
      - /app/node_modules
    #volumes act like a pointer or referent to current dir
    #and copy it to the app dir
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
